apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: codeflare-stack-config
  envs:
    - params.env
configurations:
  - params.yaml

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: codeflare-stack-config
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- ../default
- codeflare-notebook-imagestream.yaml
